# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1351b56c44e589b724f75fd77584cd487210073773e81e49de9851a63169d330a4c06f098ef568b127c3b6b48d2b3a8525210adf8329f9c6d2997b29652dd503

test:
  secret_key_base: ab45030c147eda9d7d8514c0c401e9e743a99c0aa9151431431e8b4317f12da4bff0bf23e71b3a2508a842c11257235ee76f891ada17fb5a00fe71a4826730f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
